### PR TITLE
enabled button 15 constant

### PR DESCRIPTION
**Pull request by mardaravicius**
the comment states incorrectly that button 15 does not work. but in my testing it does and I even use it for a custom back button. did it all with triggers only.

{68DD6585-6F55-45FF-AF7F-B1D66DD51CA3}

### CODE REVIEW

**Comment by mardaravicius** [comment]
also dock second page uses buttons 21-35. maybe can also be added?

**Comment by KSneijders** [comment]
Wow, this must've changed somewhere in the past. This definitely didn't work when the 15th location was commented out. 

I'll take a look later (currently on phone) but thanks for the PR! 🤩

**Comment by KSneijders** [comment]
> also dock second page uses buttons 21-35. maybe can also be added?

I don't have much time to test at the moment, could you try and see if that works using triggers etc? Ideally provide a small script so I can test it too?

**Comment by mardaravicius** [comment]
```python
from AoE2ScenarioParser.datasets.buildings import BuildingInfo
from AoE2ScenarioParser.datasets.heroes import HeroInfo
from AoE2ScenarioParser.datasets.trigger_lists import ObjectAttribute
from AoE2ScenarioParser.scenarios.aoe2_scenario import AoE2Scenario


def main():
    scenario_dir = "D:\\drives\\Dropbox\\Saves\\age_of_empires2\\scenario\\test_button.aoe2scenario"
    scenario = AoE2Scenario.from_file(scenario_dir, game_version='DE')
    trigger = scenario.trigger_manager.add_trigger("Test")
    units = [
        HeroInfo.KHOSRAU,
        HeroInfo.LEIF_ERIKSON,
        HeroInfo.RICHARD_THE_LIONHEART,
        HeroInfo.THE_BLACK_PRINCE,
        HeroInfo.FRIAR_TUCK,
        HeroInfo.SHERIFF_OF_NOTTINGHAM,
        HeroInfo.CHARLEMAGNE,
        HeroInfo.ROLAND,
        HeroInfo.BELISARIUS,
        HeroInfo.THEODORIC_THE_GOTH,
        HeroInfo.AETHELFRITH,
        HeroInfo.SIEGFRIED,
        HeroInfo.ERIK_THE_RED,
        HeroInfo.TAMERLANE,
        HeroInfo.KING_ARTHUR,
        HeroInfo.LANCELOT,
    ]
    for i, unit in enumerate(units):
        trigger.new_effect.modify_attribute(
            source_player=1,
            object_list_unit_id=unit.ID,
            object_attributes=ObjectAttribute.TRAIN_LOCATION,
            quantity=BuildingInfo.DOCK.ID,
        )
        trigger.new_effect.modify_attribute(
            source_player=1,
            object_list_unit_id=unit.ID,
            object_attributes=ObjectAttribute.TRAIN_BUTTON,
            quantity=i + 20,
        )
        trigger.new_effect.enable_disable_object(
            source_player=1,
            object_list_unit_id=unit.ID,
            enabled=True,
        )
    scenario.write_to_file(scenario_dir)


if __name__ == '__main__':
    main()

```

**Comment by KSneijders** [comment]
@mardaravicius Awesome! Thank you! About buttons 21-35 how would you imagine they'd be work? 

Something like `ButtonLocation.r1c1.page2`?

Would you agree?

```py
    @property
    def page2(self):
        """
        Returns the button location for the second page.
        Used as a suffix to the usual button selection: ``ButtonLocation.r1c1.page2``

        Returns:
            The value representing the button location for the second page
        """
        return self.value + 20

```

**Comment by mardaravicius** [comment]
sure. but might even say dock? since this behavior seems to only be for dock/harbor. for instance, buildings page2 still uses 1-15 but you also need to change another variable (which is not possible via triggers) 🤷

**Comment by kerwin-wildsea** [comment]
@mardaravicius Sorry, I don't quite follow right now. Previously you mentioned that it uses 21-35 now you're saying 1-15. 

The reason I'm asking is if it cannot be used in scenarios (with triggers) there's no point in adding the entries to the dataset

**Comment by KSneijders** [comment]
@mardaravicius Sorry, I don't quite follow right now. Previously you mentioned that it uses 21-35 now you're saying 1-15. 
The reason I'm asking is if it cannot be used in scenarios (with triggers) there's no point in adding the entries to the dataset

Edit: Did you mean that: other buildings besides dock/harbor still use 1-15 for page2?

**Comment by mardaravicius** [comment]
I am saying that for buildings the second page also uses 1-15 + interface_kind = 10
but for dock/harbor units it uses 20-35 and ignores interface_kind
so it's not universal.
and these are the only 2 cases of 2 pages that I know.
in scenario editor triggers you can add units to the second page of a dock, but can't add buildings to the second page of a villager build (or at least I don't know how)
so maybe just call dock_page2? or have comments that explains that it only works for docks

**Comment by KSneijders** [comment]
@mardaravicius Alright, yes. Thanks for the clarification! ❤️ 

Calling it something like `dock_page2` is a good call.

**Pull request merged**
